apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgCK8O2gK6b0P7JujCg7zfvBmLFpE+Dg4qBFaPVdXDX5NfNSTJUi0MAcfbT4TkAjsCnTJFUXt0LWyWCpW1M2sp9GBpnw33bZn8kVqq0ewyPDKjTmBVI3gGE3S8sOT7liKijn1eM4sn/+g290Fb5+BZ2JXnqNgvKmH7vo+Wm6lbCHXhK2tZcjnqG5Taa56WOJiRca9QJW/4Z73S1EgvE9n3Wn32ONN8cnPqp0MrtDV1FRkI8DPAwjJu+CFNAitZWYVqNHMG/rcdfUlJrr4Dt1fYRc5cPCgGg/CTXguUbQczOLLmudwnZoNRgWWy71k669YEUX1UImhep+hwkm3mRTCwKFgb9HfLeM4f6tps5mDBEBGzt8Z1eovClMatZ7ZeobXTMp3moOXSCvNlchs1xykhOuBVBvLyZExJ/65amSeiZOeiDZmK5/HC9WDq6srz5uR5UsufCsdJ9clexi35Dm7lM9UzoAtM6cgUxOypb7wQWu3vS62+PpRuGL4OJEjaCEkHYYGNv2j4xpopxV9TagGWRB+usVxYbEw2kDIQtLoVme2jM4E0dKfC6vX9aQyr2bciFzXLQyTQXZLfij31BctRz9eIP8rGzN4zYzoru8zBKhCUlXBS5r3TJ2Sf+vgC8sQstGmN2IVLYUUCEws/ZjGdpCgEskaJeYXRycKyIOmmS4U3CzVhfv+NdYNQhssW06vIO4qmukOgctjA==
    user: AgAyda3mwVaMy4C8Xc4EiLuLLnUrtWVAEwDjAdCxDujOu0skQvx0wgwlIjE11aQecwHxVKTxLqGVilGe5GA9DO79okKU61XQvFaCkmlLEs+l4ubW6Ew0xQKje/Vz7dvm55JdXfwflDW7Blh9QorxOkzDQJhEc4pHmQyo6Rpc7yldr8JQVRYuAddHVu81boEKkEnNzNcEVhb7ZZXwJISjIjbTAJ6GG0TPZJBFWUCxtwDRnUlW6rK48sPK03hx6VCHCC2kRyFGqGs7+JpaLyLK212h3lJYhApFs0gHNhN6bNmOFXddzRDPcfrMkrlg7LO8BeQO8hbf1beBvI3r9NQSEwzhKWqQyjSGKT6VFtyKLxHvQnQYUqTkbeVlg0cM+sF3naRWB7gKG9KoGAQ9kLzagLXU/E1+cUznO1ek9yG7IAEdyWrjy4rlNjfmUt04eAELiKnw6K5+V1KldR4ucAx34dZks7yBebkL0q3aYSGAkpznsd6lznaqvqKsyzVbwZBTx/U+gUL265g30i/MhhL1JFEZ91ab+DRXRZTgWZhh1lQBnvoUeDrRz6vb4p2nA1brSQ0R2Py4YjmyURnOiljfnfRmD4JI0y6vGmIpQ50rdoQwUXN+KE3vHK01QcOvHzoaS8DYmXb8CtuQ4m2EWeoOn7i/HDzpW4FFALrv97W+IqL3BexxQUMsDrcLsbEGaXrq+tgCq0yJ6Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default

