---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
   chart: nginx
   sourceRef:
      kind: HelmRepository
      name: bitnami
      tags: 9.7.0  
   interval: 1m0s
   releaseName: nginx
